<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Skyline.DataMiner.CICD.FileSystem</AssemblyName>
    <RootNamespace>Skyline.DataMiner.CICD.FileSystem</RootNamespace>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>SkylineCommunications</Authors>
    <Company>Skyline Communications</Company>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageIcon>icon.png</PackageIcon>
    <PackageProjectUrl>https://skyline.be/</PackageProjectUrl>
    <PackageTags>Skyline;DataMiner;CICD</PackageTags>
    <Description>Library providing methods to access the FileSystem on both Unix or Windows systems through a single interface. It also allows manipulation of Windows paths from Linux or Linux paths from Windows. For Windows it also provides support for paths larger than 260 characters.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/SkylineCommunications/Skyline.DataMiner.CICD.FileSystem</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <SignAssembly>True</SignAssembly>
    <DelaySign>False</DelaySign>
    <AssemblyOriginatorKeyFile>..\StrongName.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="" />
    <None Include="..\_NuGetItems\icon.png" Pack="true" PackagePath="" />
    <None Include="..\_NuGetItems\LICENSE.txt" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AlphaFS.New" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FileSystemTests, PublicKey=002400000480000094000000060200000024000052534131000400000100010035a9e1704481c9042f3e4f298e5d4f8232b6dbde1b342e0148523a0ad054eaa02d6626b7d1bec8ee247376f5ed49bda8b540c3234830247405149f8812f34d4d0fc15dedb5f7147d5a7cc9290b631ec51ee92b4e8e216e7d315c4db3dbbc30121c93205606071e4aa2521a6e660bb6429532e7278efabc0f448c0bef3e4d1aa2" />
  </ItemGroup>

</Project>
